version: '3.8'

services:
  medibook-app:
    image: YOUR_DOCKERHUB_USERNAME/medibook-api:latest
    container_name: student1_medibook
    ports:
      - "9001:3090"
    env_file:
      - .env
    restart: always
    networks:
      - classroom_net

networks:
  classroom_net:
    name: classroom_classroom_net
    external: true
